// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	PasswordHash      string
	Provider          *string
	ProviderAccountID *string
	CreatedAt         *time.Time
	UpdatedAt         *time.Time
}

type Permission struct {
	ID             uuid.UUID
	PermissionName string
	Module         string
	Act            string
	CreatedAt      *time.Time
	DeletedAt      *time.Time
}

type Role struct {
	ID        uuid.UUID
	RoleName  string
	RoleCode  *string
	CreatedAt *time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}

type RolePermission struct {
	ID           uuid.UUID
	PermissionID uuid.UUID
	RoleID       uuid.UUID
	CreatedAt    *time.Time
	DeletedAt    *time.Time
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ActiveRole *uuid.UUID
	TokenHash  string
	CsrfToken  string
	IpAddress  string
	UserAgent  string
	CreatedAt  *time.Time
	ExpiredAt  *time.Time
}

type User struct {
	ID            uuid.UUID
	Fullname      string
	Username      string
	Email         string
	VerifiedEmail bool
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	DeletedAt     *time.Time
}

type UserPermission struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    *time.Time
	DeletedAt    *time.Time
}

type UserRole struct {
	ID        uuid.UUID
	RoleID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt *time.Time
	DeletedAt *time.Time
}
