// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const findUser = `-- name: FindUser :one
SELECT id, fullname, username, email, verified_email, created_at, updated_at, deleted_at FROM users
WHERE id = $1
`

func (q *Queries) FindUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Email,
		&i.VerifiedEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUsers = `-- name: FindUsers :many
SELECT id, fullname, username, email, verified_email, created_at, updated_at, deleted_at FROM users
`

func (q *Queries) FindUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, findUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Username,
			&i.Email,
			&i.VerifiedEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts
(user_id, password_hash, provider, provider_account_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertAccountParams struct {
	UserID            uuid.UUID
	PasswordHash      string
	Provider          *string
	ProviderAccountID *string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.UserID,
		arg.PasswordHash,
		arg.Provider,
		arg.ProviderAccountID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions
(user_id, active_role, token_hash, csrf_token, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertSessionParams struct {
	UserID     uuid.UUID
	ActiveRole *uuid.UUID
	TokenHash  string
	CsrfToken  string
	IpAddress  string
	UserAgent  string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.UserID,
		arg.ActiveRole,
		arg.TokenHash,
		arg.CsrfToken,
		arg.IpAddress,
		arg.UserAgent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users
(fullname, username, email, verified_email)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertUserParams struct {
	Fullname      string
	Username      string
	Email         string
	VerifiedEmail bool
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Fullname,
		arg.Username,
		arg.Email,
		arg.VerifiedEmail,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
