// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const findRoles = `-- name: FindRoles :many
SELECT id, role_name, role_code, created_at, updated_at, deleted_at FROM roles
`

func (q *Queries) FindRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, findRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.RoleCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRole = `-- name: InsertRole :one
INSERT INTO roles
(role_name, role_code)
VALUES ($1, $2)
RETURNING id
`

type InsertRoleParams struct {
	RoleName string
	RoleCode *string
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRole, arg.RoleName, arg.RoleCode)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
