// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type EffectPermission string

const (
	EffectPermissionGrant EffectPermission = "grant"
	EffectPermissionDeny  EffectPermission = "deny"
)

func (e *EffectPermission) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EffectPermission(s)
	case string:
		*e = EffectPermission(s)
	default:
		return fmt.Errorf("unsupported scan type for EffectPermission: %T", src)
	}
	return nil
}

type NullEffectPermission struct {
	EffectPermission EffectPermission
	Valid            bool // Valid is true if EffectPermission is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEffectPermission) Scan(value interface{}) error {
	if value == nil {
		ns.EffectPermission, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EffectPermission.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEffectPermission) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EffectPermission), nil
}

type RoleType string

const (
	RoleTypeSystem RoleType = "system"
	RoleTypeDomain RoleType = "domain"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType
	Valid    bool // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type Permission struct {
	ID             uuid.UUID
	PermissionName string
	Module         string
	Act            string
	IsActive       bool
	CreatedAt      *time.Time
}

type Role struct {
	ID           uuid.UUID
	RoleName     string
	RoleCode     string
	RoleCategory RoleType
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    *time.Time
}

type RolePermission struct {
	ID           uuid.UUID
	PermissionID uuid.UUID
	RoleID       uuid.UUID
	CreatedAt    *time.Time
	DeletedAt    *time.Time
}

type User struct {
	ID            uuid.UUID
	Fullname      string
	Username      string
	Email         string
	VerifiedEmail bool
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	DeletedAt     *time.Time
	LastLoginAt   *time.Time
}

type UserAccount struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	PasswordHash      *string
	Provider          string
	ProviderAccountID *string
	CreatedAt         *time.Time
	UpdatedAt         *time.Time
}

type UserPermission struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	PermissionID uuid.UUID
	Effect       EffectPermission
	Reasons      *string
	CreatedBy    uuid.UUID
	ExpiresAt    *time.Time
	CreatedAt    *time.Time
	DeletedAt    *time.Time
}

type UserRole struct {
	ID        uuid.UUID
	RoleID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt *time.Time
	DeletedAt *time.Time
}

type UserSession struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ActiveRole *uuid.UUID
	TokenHash  string
	CsrfToken  *string
	IpAddress  netip.Addr
	UserAgent  string
	CreatedAt  *time.Time
	ExpiresAt  time.Time
}
