// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sqlc_rbac.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const rBACInsertRole = `-- name: RBACInsertRole :one
INSERT INTO roles
    (role_name, role_code)
VALUES
    ($1, $2)
RETURNING id
`

type RBACInsertRoleParams struct {
	RoleName string
	RoleCode string
}

func (q *Queries) RBACInsertRole(ctx context.Context, arg RBACInsertRoleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, rBACInsertRole, arg.RoleName, arg.RoleCode)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
