// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sqlc_auth.sql

package queries

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const deleteAllSessionsByUserID = `-- name: DeleteAllSessionsByUserID :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteAllSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsByUserID, userID)
	return err
}

const deleteExpiredSessionsByUser = `-- name: DeleteExpiredSessionsByUser :exec
DELETE FROM user_sessions
WHERE user_id = $1 AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessionsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessionsByUser, userID)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM user_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteSessionsBeyondLimit = `-- name: DeleteSessionsBeyondLimit :exec
DELETE FROM user_sessions
WHERE id IN (
    SELECT s.id
    FROM user_sessions s
    WHERE s.user_id = $1
    ORDER BY s.created_at DESC
    OFFSET $2
)
`

type DeleteSessionsBeyondLimitParams struct {
	UserID uuid.UUID
	Offset int32
}

func (q *Queries) DeleteSessionsBeyondLimit(ctx context.Context, arg DeleteSessionsBeyondLimitParams) error {
	_, err := q.db.Exec(ctx, deleteSessionsBeyondLimit, arg.UserID, arg.Offset)
	return err
}

const findAccountByUsername = `-- name: FindAccountByUsername :one
SELECT u.id AS user_id, u.username, u.email, u.verified_email, a.password_hash
FROM users u
INNER JOIN user_accounts a ON a.user_id = u.id
WHERE u.username = $1
  AND u.deleted_at IS NULL
`

type FindAccountByUsernameRow struct {
	UserID        uuid.UUID
	Username      string
	Email         string
	VerifiedEmail bool
	PasswordHash  *string
}

func (q *Queries) FindAccountByUsername(ctx context.Context, username string) (FindAccountByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findAccountByUsername, username)
	var i FindAccountByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.VerifiedEmail,
		&i.PasswordHash,
	)
	return i, err
}

const findActiveSessionsByUserID = `-- name: FindActiveSessionsByUserID :many
SELECT id, ip_address, user_agent, active_role, created_at, expires_at
FROM user_sessions
WHERE user_id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

type FindActiveSessionsByUserIDRow struct {
	ID         uuid.UUID
	IpAddress  netip.Addr
	UserAgent  string
	ActiveRole *uuid.UUID
	CreatedAt  *time.Time
	ExpiresAt  time.Time
}

func (q *Queries) FindActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]FindActiveSessionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, findActiveSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindActiveSessionsByUserIDRow
	for rows.Next() {
		var i FindActiveSessionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.UserAgent,
			&i.ActiveRole,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT id, user_id, expires_at, active_role
FROM user_sessions
WHERE token_hash = $1
`

type FindSessionByTokenHashRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ExpiresAt  time.Time
	ActiveRole *uuid.UUID
}

func (q *Queries) FindSessionByTokenHash(ctx context.Context, tokenHash string) (FindSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHash, tokenHash)
	var i FindSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.ActiveRole,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, fullname, username, email, verified_email
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type FindUserByIDRow struct {
	ID            uuid.UUID
	Fullname      string
	Username      string
	Email         string
	VerifiedEmail bool
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Email,
		&i.VerifiedEmail,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO user_accounts
(user_id, password_hash, provider, provider_account_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertAccountParams struct {
	UserID            uuid.UUID
	PasswordHash      *string
	Provider          string
	ProviderAccountID *string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.UserID,
		arg.PasswordHash,
		arg.Provider,
		arg.ProviderAccountID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO user_sessions
(user_id, active_role, token_hash, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSessionParams struct {
	UserID     uuid.UUID
	ActiveRole *uuid.UUID
	TokenHash  string
	IpAddress  netip.Addr
	UserAgent  string
	ExpiresAt  time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.UserID,
		arg.ActiveRole,
		arg.TokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const updateLastLoginAt = `-- name: UpdateLastLoginAt :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLoginAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLoginAt, id)
	return err
}
