// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sqlc_user.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const assignPermissionToUser = `-- name: AssignPermissionToUser :one

INSERT INTO user_permissions
    (user_id, permission_id)
VALUES
    ($1, $2)
RETURNING id
`

type AssignPermissionToUserParams struct {
	UserID       uuid.UUID
	PermissionID uuid.UUID
}

// =====================================================================
// USER PERMISSIONS (direct permissions attached to a user)
// =====================================================================
func (q *Queries) AssignPermissionToUser(ctx context.Context, arg AssignPermissionToUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, assignPermissionToUser, arg.UserID, arg.PermissionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const assignRoleToUser = `-- name: AssignRoleToUser :one

INSERT INTO user_roles
    (user_id, role_id)
VALUES
    ($1, $2)
RETURNING id
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

// =====================================================================
// USER ROLES
// =====================================================================
func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsUserByEmail = `-- name: ExistsUserByEmail :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email = $1
      AND deleted_at IS NULL
)
`

func (q *Queries) ExistsUserByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserByUsername = `-- name: ExistsUserByUsername :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE username = $1
      AND deleted_at IS NULL
)
`

func (q *Queries) ExistsUserByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserRole = `-- name: ExistsUserRole :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles
    WHERE user_id = $1
      AND role_id = $2
      AND deleted_at IS NULL
)
`

type ExistsUserRoleParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) ExistsUserRole(ctx context.Context, arg ExistsUserRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserRole, arg.UserID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findDirectPermissionsByUserID = `-- name: FindDirectPermissionsByUserID :many
SELECT p.id, p.permission_name, p.module, p.act, p.is_active, p.created_at
FROM permissions p
INNER JOIN user_permissions up ON up.permission_id = p.id
WHERE up.user_id = $1
  AND up.deleted_at IS NULL
  AND p.deleted_at IS NULL
ORDER BY p.module, p.act
`

func (q *Queries) FindDirectPermissionsByUserID(ctx context.Context, userID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, findDirectPermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.PermissionName,
			&i.Module,
			&i.Act,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEffectivePermissionsByUserID = `-- name: FindEffectivePermissionsByUserID :many
SELECT DISTINCT p.id, p.permission_name, p.module, p.act, p.is_active, p.created_at
FROM permissions p
LEFT JOIN role_permissions rp ON rp.permission_id = p.id
LEFT JOIN user_roles ur       ON ur.role_id = rp.role_id
LEFT JOIN user_permissions up ON up.permission_id = p.id
WHERE p.deleted_at IS NULL
  AND (
        (ur.user_id = $1 AND ur.deleted_at IS NULL AND rp.deleted_at IS NULL)
     OR (up.user_id = $1 AND up.deleted_at IS NULL)
  )
ORDER BY p.module, p.act
`

func (q *Queries) FindEffectivePermissionsByUserID(ctx context.Context, userID uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, findEffectivePermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.PermissionName,
			&i.Module,
			&i.Act,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRoles = `-- name: FindRoles :many
SELECT id, role_name, role_code, role_category, is_active, created_at, updated_at
FROM roles
WHERE deleted_at IS NULL
`

func (q *Queries) FindRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, findRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.RoleCode,
			&i.RoleCategory,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRolesByUserID = `-- name: FindRolesByUserID :many
SELECT r.id, r.role_name, r.role_code, r.role_category, r.is_active, r.created_at, r.updated_at
FROM roles r
INNER JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
  AND ur.deleted_at IS NULL
  AND r.deleted_at IS NULL
ORDER BY r.role_name
`

func (q *Queries) FindRolesByUserID(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, findRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.RoleName,
			&i.RoleCode,
			&i.RoleCategory,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUser = `-- name: FindUser :one

SELECT id, fullname, username, email, verified_email, created_at, updated_at, deleted_at, last_login_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

// =====================================================================
// USERS
// =====================================================================
func (q *Queries) FindUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Email,
		&i.VerifiedEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, fullname, username, email, verified_email, created_at, updated_at, deleted_at, last_login_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Email,
		&i.VerifiedEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, fullname, username, email, verified_email, created_at, updated_at, deleted_at, last_login_at
FROM users
WHERE username = $1
  AND deleted_at IS NULL
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Email,
		&i.VerifiedEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const findUsers = `-- name: FindUsers :many
SELECT id, fullname, username, email, verified_email, created_at, updated_at, deleted_at, last_login_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) FindUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, findUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Username,
			&i.Email,
			&i.VerifiedEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUsersPaginated = `-- name: FindUsersPaginated :many
SELECT id, fullname, username, email, verified_email, created_at, updated_at, deleted_at, last_login_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type FindUsersPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) FindUsersPaginated(ctx context.Context, arg FindUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, findUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Username,
			&i.Email,
			&i.VerifiedEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) HardDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteUser, id)
	return err
}

const insertRole = `-- name: InsertRole :one

INSERT INTO roles
    (role_name, role_code, role_category)
VALUES
    ($1, $2, $3)
RETURNING id
`

type InsertRoleParams struct {
	RoleName     string
	RoleCode     string
	RoleCategory RoleType
}

// =====================================================================
// ROLES
// =====================================================================
func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRole, arg.RoleName, arg.RoleCode, arg.RoleCategory)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users
    (fullname, username, email, verified_email)
VALUES
    ($1, $2, $3, $4)
RETURNING id
`

type InsertUserParams struct {
	Fullname      string
	Username      string
	Email         string
	VerifiedEmail bool
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Fullname,
		arg.Username,
		arg.Email,
		arg.VerifiedEmail,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const removeAllRolesFromUser = `-- name: RemoveAllRolesFromUser :exec
UPDATE user_roles
SET deleted_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) RemoveAllRolesFromUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllRolesFromUser, userID)
	return err
}

const removePermissionFromUser = `-- name: RemovePermissionFromUser :exec
UPDATE user_permissions
SET deleted_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND permission_id = $2
  AND deleted_at IS NULL
`

type RemovePermissionFromUserParams struct {
	UserID       uuid.UUID
	PermissionID uuid.UUID
}

func (q *Queries) RemovePermissionFromUser(ctx context.Context, arg RemovePermissionFromUserParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromUser, arg.UserID, arg.PermissionID)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
UPDATE user_roles
SET deleted_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND role_id = $2
  AND deleted_at IS NULL
`

type RemoveRoleFromUserParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET deleted_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE roles
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteRole, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET fullname   = $2,
    username   = $3,
    email      = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserParams struct {
	ID       uuid.UUID
	Fullname string
	Username string
	Email    string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Fullname,
		arg.Username,
		arg.Email,
	)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET verified_email = TRUE,
    updated_at     = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
